const API_KEY = process.env.API_KEY;
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Nav from "../components/Nav";
import Movies from "../components/movies";
import axios from "axios";

export default function Home({movies}) {
  return (
    <div>
      <Head>
        <title>movies-info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Nav */}
      <Nav />
      {/* Movies */}
      <Movies movies={movies}/>
      {/* Footer */}
      <Footer />
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const query = context.query.s ||"vikings";
  console.log(context.query);

  let request

  if ('s' in context.query){
     request = await axios
    .get(
      `https://www.omdbapi.com/?s=${query}&?type=series&?y=2016&apikey=${API_KEY}`
    )
  }
  if ('i' in context.query){
     request = await axios
    .get(
      `https://www.omdbapi.com/?i=${query}&apikey=${API_KEY}`
    )
    console.log("here is the id request");
  }
  request = await axios
  .get(
    `https://www.omdbapi.com/?s=${query}&?type=series&?y=2016&apikey=${API_KEY}`
  )



  console.log(request, "dflsdf");
  return {
    props: {
      movies: request.data,
    },
  };
};
